import '../../../data/models/product.dart';

/// Sample products data for POS
List<Product> getSamplePOSProducts() {
  return [
    Product(
      id: 1,
      itemCode: 'PNT001-BOY-WHT-1L',
      name: 'Boysen Premium White 1L',
      description: 'Premium quality latex white paint, 1 liter',
      category: 'Paint & Finishing',
      subcategory: 'Interior Paint',
      brand: 'Boysen',
      specifications: '1L, White, Latex',
      unit: 'liter',
      costPrice: 150,
      markupPercent: 30,
      sellingPrice: 195,
      stock: 80,
      reorderLevel: 20,
      reorderQuantity: 50,
      supplier: 'Supplier A - Boysen Paint Center',
      supplierCode: 'SUP-A',
      location: 'Aisle 1-A',
      taxable: true,
    ),
    Product(
      id: 12,
      itemCode: 'CMT001-HOL-PTL-40KG',
      name: 'Holcim Portland Cement 40kg',
      description: 'Type 1 Portland cement, 40kg bag',
      category: 'Cement',
      subcategory: 'Portland Cement',
      brand: 'Holcim',
      specifications: '40kg, Type 1',
      unit: 'bag',
      costPrice: 220,
      markupPercent: 20,
      sellingPrice: 264,
      stock: 450,
      reorderLevel: 100,
      reorderQuantity: 200,
      supplier: 'Supplier C - Holcim Philippines',
      supplierCode: 'SUP-C',
      location: 'Warehouse Zone A',
      taxable: true,
    ),
    Product(
      id: 17,
      itemCode: 'STL001-PAG-RBR-10MM',
      name: 'Pag-asa Steel 10mm Rebar',
      description: 'Deformed steel rebar, 10mm diameter, 6 meters',
      category: 'Steel',
      subcategory: 'Rebar',
      brand: 'Pag-asa Steel',
      specifications: '10mm x 6m, Grade 40',
      unit: 'piece',
      costPrice: 250,
      markupPercent: 20,
      sellingPrice: 300,
      stock: 15,
      reorderLevel: 200,
      reorderQuantity: 500,
      supplier: 'Supplier G - Pag-asa Steel Corp',
      supplierCode: 'SUP-G',
      location: 'Warehouse Zone B',
      taxable: true,
    ),
    Product(
      id: 21,
      itemCode: 'WOD001-LCL-2X2-8FT',
      name: 'Local Timber 2x2 Lumber (8ft)',
      description: 'Kiln-dried lumber, 2x2 inches, 8 feet',
      category: 'Wood',
      subcategory: 'Lumber',
      brand: 'Local Timber',
      specifications: '2x2" x 8ft, Kiln-dried',
      unit: 'piece',
      costPrice: 120,
      markupPercent: 35,
      sellingPrice: 162,
      stock: 500,
      reorderLevel: 80,
      reorderQuantity: 200,
      supplier: 'Supplier F - Local Timber Supply',
      supplierCode: 'SUP-F',
      location: 'Warehouse Zone C',
      taxable: true,
    ),
    // Add out of stock example
    Product(
      id: 99,
      itemCode: 'TST-OUT-STOCK',
      name: 'Out of Stock Item',
      description: 'Test item with no stock',
      category: 'Tools',
      subcategory: 'Hand Tools',
      brand: 'Test Brand',
      specifications: 'N/A',
      unit: 'piece',
      costPrice: 100,
      markupPercent: 25,
      sellingPrice: 125,
      stock: 0,
      reorderLevel: 10,
      reorderQuantity: 20,
      supplier: 'Test Supplier',
      supplierCode: 'TEST',
      location: 'Test',
      taxable: true,
    ),
  ];
}
