# Generated by Django 4.2.30 on 2026-05-14 01:43

from django.db import migrations, models


def seed_projects(apps, schema_editor):
    Project = apps.get_model("projectm", "Project")
    Project.objects.update_or_create(
        name="Skyline Tower Phase 2",
        defaults={
            "client": "Urban Developments Inc.",
            "foreman": "Juan Dela Cruz",
            "status": "In Progress",
            "location": "1250 Metro Avenue, Business District, Metro Manila",
            "progress": 68,
            "budget_materials": 500000,
            "budget_labor": 250000,
            "budget_equipment": 100000,
            "start_date": "2026-01-15",
            "deadline": "2026-04-30",
            "materials": [
                {
                    "id": 1,
                    "name": "Steel Beams",
                    "category": "Steel",
                    "quantityRequired": 200,
                    "quantityReceived": 150,
                    "used": 150,
                    "available": 0,
                    "unitCost": 2500,
                    "unit": "pieces",
                    "status": "OUT",
                },
                {
                    "id": 2,
                    "name": "Cement Bags",
                    "category": "Cement",
                    "quantityRequired": 600,
                    "quantityReceived": 500,
                    "used": 425,
                    "available": 75,
                    "unitCost": 300,
                    "unit": "bags",
                    "status": "LOW",
                },
            ],
            "expenses": [
                {
                    "id": 1,
                    "date": "2026-04-20",
                    "category": "Materials",
                    "description": "Steel beam delivery batch 3",
                    "amount": 375000,
                    "addedBy": "Admin",
                },
            ],
            "progress_logs": [
                {
                    "id": 1,
                    "date": "2026-04-20",
                    "type": "Weekly",
                    "description": (
                        "Foundation completed, steel framing 60% done. "
                        "Weather conditions favorable this week."
                    ),
                    "completedTasks": [
                        "Foundation concrete pour completed",
                        "Steel beam installation level 1-3",
                        "Electrical conduit installation started",
                        "Plumbing rough-in for ground floor",
                    ],
                    "issues": [
                        "Delay in steel delivery by 2 days",
                        "Minor equipment malfunction - resolved",
                    ],
                },
            ],
            "issues": [
                {
                    "id": 1,
                    "title": "Steel beam shortage",
                    "type": "Shortage",
                    "description": (
                        "Need 50 more steel beams for upper floors. Current "
                        "supplier cannot deliver until next week."
                    ),
                    "status": "Open",
                    "reportedDate": "2026-04-22",
                    "reportedBy": "Juan Dela Cruz",
                    "priority": "High",
                },
            ],
            "comments": [
                {
                    "id": 1,
                    "author": "Admin",
                    "content": (
                        "Please prioritize steel beam procurement for next week. "
                        "Check with alternative suppliers."
                    ),
                    "timestamp": "2026-04-23 10:30 AM",
                },
            ],
        },
    )


def unseed_projects(apps, schema_editor):
    Project = apps.get_model("projectm", "Project")
    Project.objects.filter(name="Skyline Tower Phase 2").delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('foreman', models.CharField(max_length=255)),
                ('status', models.CharField(default='Planning', max_length=64)),
                ('location', models.CharField(max_length=255)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('budget_materials', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('budget_labor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('budget_equipment', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('materials', models.JSONField(blank=True, default=list)),
                ('expenses', models.JSONField(blank=True, default=list)),
                ('progress_logs', models.JSONField(blank=True, default=list)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('comments', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.RunPython(seed_projects, unseed_projects),
    ]
