# Generated by Django 4.2.30 on 2026-05-08 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=128)),
                ('subcategory', models.CharField(blank=True, default='', max_length=128)),
                ('brand', models.CharField(blank=True, default='', max_length=128)),
                ('specifications', models.TextField(blank=True, default='')),
                ('unit', models.CharField(blank=True, default='unit', max_length=64)),
                ('cost_price', models.FloatField(default=0)),
                ('markup_percent', models.FloatField(default=0)),
                ('selling_price', models.FloatField(default=0)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=20)),
                ('reorder_quantity', models.PositiveIntegerField(default=50)),
                ('supplier', models.CharField(blank=True, default='', max_length=255)),
                ('supplier_code', models.CharField(blank=True, max_length=64, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=128, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=64, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('barcode', models.CharField(blank=True, max_length=128, null=True)),
                ('taxable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=255)),
                ('supplier_code', models.CharField(blank=True, max_length=64, null=True)),
                ('warehouse_location', models.CharField(blank=True, default='', max_length=255)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=128)),
                ('received_by', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('line_count', models.PositiveIntegerField(default=0)),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='StockReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_lines', to='inventory.product')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockreceipt')),
            ],
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('item_code',), name='inventory_product_item_code_unique'),
        ),
    ]
