# Generated by Codex on 2026-05-14

from django.db import migrations, models


DEFAULT_SUPPLIERS = [
    {
        "code": "SUP-A",
        "name": "Supplier A - Boysen Paint Center",
        "contact": "(02) 8888-1234",
        "email": "orders@boysen.com.ph",
        "payment_terms": "Net 30",
        "lead_time_days": 3,
        "categories": ["Paint & Finishing"],
    },
    {
        "code": "SUP-B",
        "name": "Supplier B - Nippon Distributors",
        "contact": "(02) 8888-2345",
        "email": "sales@nippon.com.ph",
        "payment_terms": "Net 30",
        "lead_time_days": 3,
        "categories": ["Paint & Finishing"],
    },
    {
        "code": "SUP-C",
        "name": "Supplier C - Holcim Philippines",
        "contact": "(02) 8888-3456",
        "email": "orders@holcim.ph",
        "payment_terms": "Net 45",
        "lead_time_days": 5,
        "categories": ["Cement"],
    },
    {
        "code": "SUP-D",
        "name": "Supplier D - Republic Cement",
        "contact": "(02) 8888-4567",
        "email": "sales@republiccement.com",
        "payment_terms": "Net 45",
        "lead_time_days": 5,
        "categories": ["Cement"],
    },
    {
        "code": "SUP-E",
        "name": "Supplier E - Hardware Wholesale",
        "contact": "(02) 8888-5678",
        "email": "wholesale@hardware.ph",
        "payment_terms": "Net 15",
        "lead_time_days": 2,
        "categories": ["Nails & Fasteners", "Tools", "Paint & Finishing"],
    },
    {
        "code": "SUP-F",
        "name": "Supplier F - Local Timber & Quarry",
        "contact": "(02) 8888-6789",
        "email": "orders@timber.ph",
        "payment_terms": "Net 30",
        "lead_time_days": 4,
        "categories": ["Wood", "Aggregates"],
    },
    {
        "code": "SUP-G",
        "name": "Supplier G - Pag-asa Steel Corp",
        "contact": "(02) 8888-7890",
        "email": "sales@pagasasteel.com",
        "payment_terms": "Net 30",
        "lead_time_days": 4,
        "categories": ["Steel"],
    },
    {
        "code": "SUP-H",
        "name": "Supplier H - Capitol Steel",
        "contact": "(02) 8888-8901",
        "email": "orders@capitolsteel.ph",
        "payment_terms": "Net 30",
        "lead_time_days": 4,
        "categories": ["Steel"],
    },
    {
        "code": "SUP-I",
        "name": "Supplier I - Block Factory",
        "contact": "(02) 8888-9012",
        "email": "factory@blocks.ph",
        "payment_terms": "Cash",
        "lead_time_days": 1,
        "categories": ["Blocks"],
    },
    {
        "code": "SUP-J",
        "name": "Supplier J - Roofing Supply",
        "contact": "(02) 8888-0123",
        "email": "orders@roofing.ph",
        "payment_terms": "Net 30",
        "lead_time_days": 3,
        "categories": ["Roofing"],
    },
    {
        "code": "SUP-K",
        "name": "Supplier K - Electrical Supply",
        "contact": "(02) 8888-1357",
        "email": "sales@electrical.ph",
        "payment_terms": "Net 30",
        "lead_time_days": 3,
        "categories": ["Electrical"],
    },
    {
        "code": "SUP-L",
        "name": "Supplier L - Plumbing Depot",
        "contact": "(02) 8888-2468",
        "email": "orders@plumbing.ph",
        "payment_terms": "Net 30",
        "lead_time_days": 3,
        "categories": ["Plumbing"],
    },
    {
        "code": "SUP-M",
        "name": "Supplier M - Tools Distributor",
        "contact": "(02) 8888-3579",
        "email": "sales@tools.ph",
        "payment_terms": "Net 30",
        "lead_time_days": 3,
        "categories": ["Tools"],
    },
    {
        "code": "SUP-N",
        "name": "Supplier N - Safety Supply",
        "contact": "(02) 8888-4680",
        "email": "orders@safety.ph",
        "payment_terms": "Net 30",
        "lead_time_days": 2,
        "categories": ["Safety Equipment"],
    },
]


def seed_suppliers(apps, schema_editor):
    Supplier = apps.get_model("inventory", "Supplier")
    for data in DEFAULT_SUPPLIERS:
        Supplier.objects.update_or_create(code=data["code"], defaults=data)


def unseed_suppliers(apps, schema_editor):
    Supplier = apps.get_model("inventory", "Supplier")
    Supplier.objects.filter(code__in=[s["code"] for s in DEFAULT_SUPPLIERS]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_pos_sale_and_lines"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("contact", models.CharField(max_length=128)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("payment_terms", models.CharField(default="Net 30", max_length=128)),
                ("lead_time_days", models.PositiveIntegerField(default=3)),
                ("categories", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.RunPython(seed_suppliers, unseed_suppliers),
    ]
