# Generated by Django 4.2.30 on 2026-05-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
