# Generated by Django 4.2.30 on 2026-05-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('module', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=128)),
                ('summary', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True, default='')),
                ('actor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('actor_role', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
